import {
  Document,
  Packer,
  SectionType,
  Header,
  Footer,
  PageNumber,
  AlignmentType,
  Paragraph,
  TextRun,
  type FileChild,
} from 'docx';
import type { DocumentIR } from '../core/types.js';
import { createStyles } from './styles.js';
import { renderBlock } from './renderers/block.js';

export async function buildDocument(ir: DocumentIR): Promise<Document> {
  const config = ir.config;
  const styles = createStyles(config);

  // Render all blocks
  const children: FileChild[] = [];
  for (const node of ir.children) {
    const rendered = await renderBlock(node, config);
    for (const r of rendered) {
      children.push(r as FileChild);
    }
  }

  // Build header
  const header = config.headerFooter.header
    ? new Header({
        children: [
          new Paragraph({
            children: [new TextRun({ text: config.headerFooter.header })],
            alignment: AlignmentType.CENTER,
          }),
        ],
      })
    : undefined;

  // Build footer
  const footerChildren: TextRun[] = [];
  if (config.headerFooter.footer) {
    footerChildren.push(new TextRun({ text: config.headerFooter.footer }));
  }
  if (config.headerFooter.pageNumbers) {
    if (footerChildren.length > 0) {
      footerChildren.push(new TextRun({ text: ' - ' }));
    }
    footerChildren.push(
      new TextRun({ text: 'Page ' }),
      new TextRun({ children: [PageNumber.CURRENT] }),
      new TextRun({ text: ' of ' }),
      new TextRun({ children: [PageNumber.TOTAL_PAGES] })
    );
  }

  const footer =
    footerChildren.length > 0
      ? new Footer({
          children: [
            new Paragraph({
              children: footerChildren,
              alignment: AlignmentType.CENTER,
            }),
          ],
        })
      : undefined;

  const section: any = {
    properties: {
      type: SectionType.CONTINUOUS,
      page: {
        margin: {
          top: config.margin.top,
          bottom: config.margin.bottom,
          left: config.margin.left,
          right: config.margin.right,
        },
        size: {
          orientation: config.orientation,
        },
      },
    },
    children,
  };

  if (header) {
    section.headers = { default: header };
  }
  if (footer) {
    section.footers = { default: footer };
  }

  return new Document({
    creator: ir.meta.author || 'Markdown to Word',
    title: ir.meta.title || 'Document',
    description: 'Generated by markdowntoword',
    styles: {
      default: {},
      paragraphStyles: styles as any,
    },
    sections: [section],
  });
}

export async function generateBuffer(ir: DocumentIR): Promise<Buffer> {
  const doc = await buildDocument(ir);
  return await Packer.toBuffer(doc);
}
